---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  vars:
    image_name: my-country-service
    image_tag: "15"
    dockerfile_path: './'
    docker_registry_username: onsnas
    docker_registry_password: "onsDocker?870."
    deployment_file: "my-deployment.yml"

  tasks:
    - name: Build Docker image
      ansible.builtin.shell: |
        docker build -t {{ docker_registry_username }}/{{ image_name }}:{{ image_tag }} {{ dockerfile_path }}

    - name: Log in to Docker Hub
      ansible.builtin.shell: |
        echo "{{ docker_registry_password }}" | docker login -u "{{ docker_registry_username }}" --password-stdin

    - name: Push Docker image
      ansible.builtin.shell: |
        docker push {{ docker_registry_username }}/{{ image_name }}:{{ image_tag }}

    - name: Update deployment YAML with correct image tag
      ansible.builtin.replace:
        path: "{{ deployment_file }}"
        regexp: "TAG_TO_REPLACE"
        replace: "{{ image_tag }}"

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: "{{ deployment_file }}"
        kubeconfig: config

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config
