---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  vars:
    image_name: my-country-service
    image_tag: "15"   # tu peux automatiser l'incr√©ment si tu veux
    dockerfile_path: './'
    docker_registry_username: onsnas
    docker_registry_password: "onsDocker?870."
    deployment_file: "my-deployment.yml"

  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes

    - name: Build and push Docker image
      community.docker.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build

    - name: Update deployment YAML with correct image tag
      ansible.builtin.replace:
        path: "{{ deployment_file }}"
        regexp: "TAG_TO_REPLACE"
        replace: "{{ image_tag }}"

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: "{{ deployment_file }}"
        kubeconfig: config

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config
