---
- name: Build, Push Docker Image and Deploy to Kubernetes
  hosts: localhost
  connection: local
  vars:
    image_name: my-country-service
    image_tag: 14
    dockerfile_path: './'
    docker_registry_username: onsnas
    docker_registry_password: 'onsDocker?870.'
  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes

    - name: Build and push Docker image
      community.docker.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build
        state: present

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: my-deployment.yml
        kubeconfig: config

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yml
        kubeconfig: config
