---
- name: Build, Push Docker Image and Deploy to Kubernetes
  hosts: localhost
  connection: local
  vars:
    image_name: my-country-service
    image_tag: 14
    dockerfile_path: './'
    docker_registry_username: onsnas
    docker_registry_password: 'onsDocker?870.'
  
  tasks:
    - name: Debug - Show current directory
      ansible.builtin.debug:
        msg: "Working directory: {{ playbook_dir }}"

    - name: Debug - List files
      ansible.builtin.command: ls -la
      register: files_list
    
    - name: Show files
      ansible.builtin.debug:
        var: files_list.stdout_lines

    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        reauthorize: yes

    - name: Build and push Docker image
      community.docker.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build
        state: present

    - name: Replace image tag in deployment
      ansible.builtin.replace:
        path: "{{ playbook_dir }}/my-deployment.yaml"
        regexp: 'TAG_TO_REPLACE'
        replace: "{{ image_tag }}"

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: "{{ playbook_dir }}/my-deployment.yaml"
        kubeconfig: "{{ playbook_dir }}/config"

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: "{{ playbook_dir }}/service.yml"
        kubeconfig: "{{ playbook_dir }}/config"